package com.ns.core.domain

enum class States {

    STARTED,BANK_ACCOUNT_CREATION_INITIATED,BANK_ACCOUNT_CREATED,BANK_ACCOUNT_CREATION_ERROR,PROFILE_CREATED,PROFILE_CREATION_ERROR,CRM_UPDATED,CRM_UPDATE_ERROR
}